[versions]
githubPackages = "1.2.1"
modDevGradle = "2.0.143"
# Mappings
parchment = "2024.11.17"
parchmentMinecraft = "1.21.1"
# Dependencies
minecraft = "1.21.1"
neoforge = "21.1.244"
patchouli = "1.21.1-93-NEOFORGE"
mixin = "0.8.5"
mixinExtras = "0.5.0"
lombok = "1.18.46"
curios = "9.5.1+1.21.1"
tfc = "p6g4aaMv"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
tfc = { group = "maven.modrinth", name = "JaCEZUhg", version.ref = "tfc" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }
mixinExtras-neoforge = { group = "io.github.llamalad7", name = "mixinextras-neoforge", version.ref = "mixinExtras" }
curios = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curios" }
patchouli = { group = "vazkii.patchouli", name = "Patchouli", version.ref = "patchouli" }

[plugins]
githubPackages = { id = "io.github.0ffz.github-packages", version.ref = "githubPackages" }
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
