modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/Traister101/Sacks-and-Such/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
logoFile = "icon.png"
authors = "Traister101"
credits = "Majority of art assets and models by Alekiponi, Boots assets by coachthesexprime. Buckle, Mob Net and Lunchbox assets created by bloodstar962"
description = '''An addon for TFC focusing on bringing vessel like handheld containers for all your adventuring needs'''

[[dependencies.${modId}]]
modId = "tfc"
type = "required"
versionRange = "[4.2.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modId}]]
modId = "esc"
type = "required"
versionRange = "[0.0.0-indev,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modId}]]
modId = "curios"
type = "optional"
versionRange = "[9.5.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sacks-n-such.mixins.json"

[mc-publish]
dependencies = [
	"tfc@4.2.4{modrinth:JaCEZUhg}{curseforge:302973}",
	"curios@9.5.1(optional){modrinth:vvuO3ImH}{curseforge:309927}"
]
